<?php
$type = $_REQUEST['type'];
$path = "/flowers".$type."image.jpg";
$descript = getcwd();
$descript .= "/flowers".$type."discription.txt";
$greet = $_REQUEST['greet'];

$descriptionarray= file($descript);	
$description = implode($descriptionarray);

echo "<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\n"; 
echo "<html xmlns=\"http://www.w3.org/1999/xhtml\">\n"; 
echo "<head>\n"; 
echo "<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\n"; 
echo "<title>Personalize your NCSU Horticulture E-Card!</title>\n"; 
echo "</head>\n"; 
echo "\n"; 
echo "<style>\n"; 
echo "/*style defaults for our page*/\n"; 
echo "html, body, h1, form, fieldset, legend, ul, li {\n"; 
echo "	margin: 0;\n"; 
echo "	padding: 0;\n"; 
echo "}\n"; 
echo "h1 {\n"; 
echo "	color: #D57500;\n"; 
echo "	font-size: 38px;\n"; 
echo "	font-weight: bold;\n"; 
echo "	font-family: Papyrus, fantasy;\n"; 
echo "	margin-top:14px;\n"; 
echo "	margin-bottom:14px;\n"; 
echo "	text-align: center;\n"; 
echo "}\n"; 
echo "body {\n"; 
echo "	background: #FFFFFF;\n"; 
echo "	color: #404F24;\n"; 
echo "	font-family: Georgia, \"Times New Roman\", Times, serif;\n"; 
echo "	padding: 20px;\n"; 
echo "}\n"; 
echo "/*style the form*/\n"; 
echo "form {\n"; 
echo "	background: #493829;\n"; 
echo "	-moz-border-radius: 15px;\n"; 
echo "	-webkit-border-radius: 15px;\n"; 
echo "	border-radius: 15px;\n"; 
echo "	border-width: 3.5px;\n"; 
echo "	border-style: solid;\n"; 
echo "	border-color: #D57500;\n"; 
echo "	padding: 12px;\n"; 
echo "	width: 460px;\n"; 
echo "}\n"; 
echo "/*remove border around each fieldset and add bottom padding*/\n"; 
echo "form fieldset {\n"; 
echo "	border: none;\n"; 
echo "	margin-bottom: 10px;\n"; 
echo "}\n"; 
echo "/*dont need bottom padding on the last fieldset tag*/\n"; 
echo "form fieldset:last-of-type {\n"; 
echo "	margin-bottom: 0;\n"; 
echo "}\n"; 
echo "/*style the form legend tags*/\n"; 
echo "form legend {\n"; 
echo "	color: #DBCA69;\n"; 
echo "	font-size: 21px;\n"; 
echo "	font-weight: bold;\n"; 
echo "	padding-bottom: 10px;\n"; 
echo "	text-shadow: 2px 3.5px 3.5px #404F24;\n"; 
echo "}\n"; 
echo "/*style the form list tags*/\n"; 
echo "form ul li {\n"; 
echo "	background: #A9A18C;\n"; 
echo "	border-color: #DBCA69;\n"; 
echo "	border-style: solid;\n"; 
echo "	border-width: 2.5px;\n"; 
echo "	-moz-border-radius: 5px;\n"; 
echo "	-webkit-border-radius: 5px;\n"; 
echo "	border-radius: 5px;\n"; 
echo "	line-height: 30px;\n"; 
echo "	list-style: none;\n"; 
echo "	padding: 5px 10px;\n"; 
echo "	margin-bottom: 5px;\n"; 
echo "}\n"; 
echo "/*style the form labels*/\n"; 
echo "form label {\n"; 
echo "	float: left;\n"; 
echo "	font-size: 13px;\n"; 
echo "	font-weight: bold;\n"; 
echo "	width: 130px;\n"; 
echo "}\n"; 
echo "/*style the last label (for captcha) to be longer*/\n"; 
echo "label:last-of-type {\n"; 
echo "\n"; 
echo "}\n"; 
echo "/*style all input and textarea elems*/\n"; 
echo "form input,\n"; 
echo "form textarea {\n"; 
echo "	background: #855723;\n"; 
echo "	border-width: 1px;\n"; 
echo "	border-color: #4E6172;\n"; 
echo "	-moz-border-radius: 4px;\n"; 
echo "	-webkit-border-radius: 4px;\n"; 
echo "	-khtml-border-radius: 4px;\n"; 
echo "	border-radius: 4px;\n"; 
echo "	font: italic 14px Georgia, \"Times New Roman\", Times, serif;\n"; 
echo "	outline: none;\n"; 
echo "	padding: 4px;\n"; 
echo "	width: 250px;\n"; 
echo "}\n"; 
echo "/*style all form input and textarea elems when selected*/\n"; 
echo "form input:focus,\n"; 
echo "form textarea:focus {\n"; 
echo "	background: #D57500;\n"; 
echo "}\n"; 
echo "/*make the last input box (for captcha) smaller*/\n"; 
echo "form input:last-of-type {\n"; 
echo "\n"; 
echo "}\n"; 
echo "/*style the form buttons*/\n"; 
echo "form button {\n"; 
echo "	background: #404F24;\n"; 
echo "	border-width: 3px;\n"; 
echo "	border-color: #668D3C;\n"; 
echo "	-moz-border-radius: 23px;\n"; 
echo "	-webkit-border-radius: 23px;\n"; 
echo "	-khtml-border-radius: 23px;\n"; 
echo "	border-radius: 23px;\n"; 
echo "	color: #BDD09F;\n"; 
echo "	display: block;\n"; 
echo "	font: 18px Georgia, \"Times New Roman\", Times, serif;\n"; 
echo "	letter-spacing: 1px;\n"; 
echo "	margin: auto;\n"; 
echo "	padding: 4px 12px;\n"; 
echo "	text-shadow: 0 2px 2px #000000;\n"; 
echo "	text-transform: uppercase;\n"; 
echo "}\n"; 
echo "/*style the form button on mouseover*/\n"; 
echo "form button:hover {\n"; 
echo "	background: #1e2506;\n"; 
echo "	cursor: pointer;\n"; 
echo "}\n"; 
echo "/*use to center objects/text*/\n"; 
echo ".centerStuff{ \n"; 
echo "	text-align: center;\n"; 
echo "}\n"; 
echo "/*specify max-width for image so it fits in the form */\n"; 
echo "img {\n"; 
echo "        max-width: 420px;\n"; 
echo "}\n"; 
echo "</style>	\n"; 
echo "\n"; 
echo "\n"; 
echo "<body>\n"; 
echo "\n"; 
echo "<form name=\"ecard\" method=\"POST\" action=\"captcha_email_send.php?image=$type&greet=$greet&desc=$description\">\n"; 
echo "<fieldset>\n"; 
echo "		<legend>1. Verify Selected E-card</legend>\n"; 
echo "		<ul>\n"; 
echo "			<li>\n"; 
echo "				<label for=greeting>Greeting:</label>\n"; 
echo "				<br>\n"; 
echo "				<h1>";
echo $greet;
echo "</h1>\n"; 
echo "			</li>\n"; 
echo "			<li>\n"; 
echo "				<label for=image>Image:</label>\n"; 
echo "				<br>\n"; 
echo "				<div class=\"centerStuff\">\n";
echo '<img src="';
    echo "http://ecard.comule.com/flowers".$type.'image.jpg">';
echo "				</div>\n"; 
echo "			</li>\n"; 
echo "			<li>\n"; 
echo "				<label for=descrip>Description:</label>\n"; 
echo "				<br>\n";
echo $description; 
echo "			</li>\n"; 
echo "		</ul>\n"; 
echo "	</fieldset>\n"; 
echo "\n"; 
echo "	<fieldset>\n"; 
echo "		<legend>2. Enter Recipient Information</legend>\n"; 
echo "		<ul>\n"; 
echo "			<li>\n"; 
echo "				<label for=\"name\">Your Name:</label>\n"; 
echo "				<input  type=\"text\" name=\"name\" placeholder=\"First & Last Name\">\n"; 
echo "			</li>\n"; 
echo "			<li>\n"; 
echo "				<label for=\"from\">From:</label>\n"; 
echo "				<input  type=\"text\" name=\"from\" placeholder=\"your_email@domain.com\">\n"; 
echo "			</li>\n"; 
echo "			<li>\n"; 
echo "				<label for=\"to\">To:</label>\n"; 
echo "				<input  type=\"text\" name=\"to\" placeholder=\"recipient_email@domain.com\">\n"; 
echo "			<li>\n"; 
echo "				<label for=\"subject\">Subject:</label>\n"; 
echo "				<input  type=\"text\" name=\"subject\">\n"; 
echo "			</li>\n"; 
echo "			<li>\n"; 
echo "				<label for=\"message\">Message:</label>\n"; 
echo "				<textarea  name=\"message\" maxlength=\"900\" rows=\"9\"></textarea>\n"; 
echo "			</li>\n"; 
echo "		</ul>\n"; 
echo "	</fieldset>\n"; 
echo "	\n"; 
echo "	<fieldset>\n"; 
echo "		<legend>3. Authenticate & Send</legend>\n"; 
echo "		<ul>					\n"; 
echo "			<li>\n"; 
echo "				<img src=\"captcha_code_file.php?rand=<?php echo rand(); ?>\" id='captchaimg' ><br>\n"; 
echo "				<label for='message'>Enter code above:</label><br>\n"; 
echo "				<input id=\"6_letters_code\" name=\"6_letters_code\" type=\"text\"><br>\n"; 
echo "				<small>Can't read the image? click <a href='javascript: refreshCaptcha();'>here</a> to refresh</small>\n"; 
echo "			</li>\n"; 
echo "		</ul>\n"; 
echo "\n"; 
echo "	</fieldset>\n"; 
echo "	\n"; 
echo "	<fieldset>\n"; 
echo "		<div class=\"centerStuff\">\n"; 
echo "		<button type=submit>Send!</button><button type=reset>Reset Form</button>\n"; 
echo "		</div>\n"; 
echo "	</fieldset>\n"; 
echo "</form>\n"; 
echo "\n"; 
echo "<script language='JavaScript' type='text/javascript'>\n"; 
echo "function refreshCaptcha()\n"; 
echo "{\n"; 
echo "	var img = document.images['captchaimg'];\n"; 
echo "	img.src = img.src.substring(0,img.src.lastIndexOf(\"?\"))+\"?rand=\"+Math.random()*1000;\n"; 
echo "}\n"; 
echo "</script>\n"; 
echo "\n"; 
echo "\n"; 
echo "</body>\n"; 
echo "</html>\n"; 
echo "\n"; 
echo "	\n";
?>